# traefik.toml

[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers.file]
  directory = "/etc/traefik/dynamic_conf"
  watch = true

[http.routers]
  [http.routers.general]
    rule = "PathPrefix(`/`)"
    service = "btfirewall"
    middlewares = ["myipwhitelist"]

[http.services]
  [http.services.btfirewall.loadBalancer]
    [[http.services.btfirewall.loadBalancer.servers]]
      url = "http://GATEWAY_IP:PORT" # Replace GATEWAY_IP and PORT

[log]
  level = "DEBUG"
