# traefik.toml

# Define the entry points for Traefik. This is where the incoming traffic will be received.
[entryPoints]
  [entryPoints.web]
    address = ":80"

# Configuration for the dynamic configuration providers.
[providers]
  # Docker provider
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

  # File provider
  [providers.file]
    directory = "/etc/traefik/dynamic_conf"
    watch = true

# Logging configuration.
[log]
  level = "DEBUG"

[accessLog]

# API and dashboard configuration.
[api]
  dashboard = true
  insecure = true
